-- 租车管理系统数据库 
-- 建表语句 每次选择一个表语句 ，运行所选，就可以在数据库中建立一个表 
CREATE TABLE users(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(100) NOT NULL UNIQUE,
Age INT NOT NULL,
Phone VARCHAR(100) NOT NULL UNIQUE,
Username VARCHAR(100) NOT NULL UNIQUE,
Password VARCHAR(100) NOT NULL 
)

CREATE TABLE cars(
ID INT PRIMARY KEY AUTO_INCREMENT,
Name VARCHAR(100) NOT NULL UNIQUE,
Price DOUBLE(11,2) NOT NULL ,
Num INT,
ImgPath VARCHAR(100)
)
CREATE TABLE sessions(
SessionID VARCHAR(100) PRIMARY KEY,
Name VARCHAR(100) NOT NULL,
UserID INT NOT NULL,
FOREIGN KEY(UserID) REFERENCES users(ID)
)
CREATE TABLE cart_items(
ID INT PRIMARY KEY AUTO_INCREMENT,
COUNT INT NOT NULL,
amount DOUBLE(11,2)NOT NULL,
car_id INT NOT NULL,
cart_id VARCHAR(100)NOT NULL,
FOREIGN KEY(car_id)REFERENCES cars(id),
FOREIGN KEY(cart_id)REFERENCES carts(id)
)

CREATE TABLE carts(
ID VARCHAR(100) PRIMARY KEY,
total_count INT NOT NULL,
total_amount DOUBLE(11,2) NOT NULL,
user_id INT NOT NULL,
FOREIGN KEY(user_id)REFERENCES users(id)
)

CREATE TABLE orders(
id VARCHAR(100) PRIMARY KEY,
create_time DATETIME NOT NULL,
total_count INT NOT NULL,
total_amount DOUBLE(11,2) NOT NULL,
state INT NOT NULL,
user_id INT,
FOREIGN KEY(user_id) REFERENCES users(id)
)

CREATE TABLE order_items(
id INT PRIMARY KEY AUTO_INCREMENT,
count INT NOT NULL,
amount DOUBLE(11,2) NOT NULL,
name VARCHAR(100) NOT NULL,
price DOUBLE(11,2)NOT NULL,
order_id VARCHAR(100) NOT NULL,
FOREIGN KEY(order_id) REFERENCES orders(id) 
)